tls_server_config: 
  cert_file: /etc/prometheus/ssl/nginx.pem
  key_file:  /etc/prometheus/ssl/nginx.key

# generate password hashes using this tool: htpasswd 
# https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md#about-bcrypt
#  
# example: 
# htpasswd -nBC 10 "" | tr -d ':\n'

# basic_auth_users:
#   admin: HASH_GOES_HERE