FROM nginx:1.27.1-alpine

# Copy over configuration files and static files
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/sites-enabled/ /etc/nginx/sites-enabled/
COPY ./nginx/conf /etc/nginx/conf.d/
COPY ./nginx/static /var/www/
COPY ./shared/ssl /etc/nginx/ssl