server:
  disable: ${PROMTAIL_HTTP_DISABLED}
  http_listen_address: ${PROMTAIL_HOST}
  http_listen_port: ${PROMTAIL_PORT}

positions:
  filename: /tmp/positions.yml

clients:
  - url: https://${LOKI_HOST}:${LOKI_PORT}/loki/api/v1/push
    basic_auth:
      username: ${LOKI_USER}
      password: ${LOKI_PASS}
    tls_config:
      insecure_skip_verify: true

scrape_configs:
  - job_name: nginx_error_${NGINX_ENV}
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_error_${NGINX_ENV}
          __path__: /mnt/logs/error.log
          host: ${NGINX_HOST}

  - job_name: nginx_access_${NGINX_ENV}
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_access_${NGINX_ENV}
          __path__: /mnt/logs/access.log
          host: ${NGINX_HOST}